name: Upload Release Asset

on:
  workflow_dispatch:

jobs:
  upload_release_asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: ./L/L_BFGS_B/products/L_BFGS_B.v3.0.1.aarch64-linux-gnu-libgfortran3.tar.gz
    asset_name: L_BFGS_B_v3.0.1_aarch64-linux-gnu-libgfortran3.tar.gz
    asset_content_type: application/gzip